services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env


  backend:
    image: ularchik/detectionrules_back
    container_name: backend
    restart: always
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started

  frontend:
    image: ularchik/detection_rules:latest
    container_name: front
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend


  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend


volumes:
  postgres_data:
