"""Add RuleModel

Revision ID: 981d9220920e
Revises: 
Create Date: 2026-05-26 11:02:21.537568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981d9220920e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('fields', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('scenario_type', sa.String(length=100), nullable=True),
    sa.Column('mitre_ids', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('tactics', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('severity_hint', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity_hint_enum'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('explanation_template', sa.String(length=500), nullable=True),
    sa.Column('recommendations', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_rules_rule_id'), 'detection_rules', ['rule_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_rules_rule_id'), table_name='detection_rules')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
