"""переименовал severity_hint severity

Revision ID: 512e372dd912
Revises: 44d8e5b20260
Create Date: 2026-09-24 15:09:49.641881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '512e372dd912'
down_revision: Union[str, Sequence[str], None] = '44d8e5b20260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correlation_rules', sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_hint_enum'), nullable=False, comment='Итоговая критичность сценария'))
    op.drop_column('correlation_rules', 'severity_hint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correlation_rules', sa.Column('severity_hint', postgresql.ENUM('info', 'low', 'medium', 'high', 'critical', name='severity_hint_enum'), autoincrement=False, nullable=False, comment='Итоговая критичность сценария'))
    op.drop_column('correlation_rules', 'severity')
    # ### end Alembic commands ###
