"""crule caudit

Revision ID: 44d8e5b20260
Revises: 
Create Date: 2026-09-24 10:33:39.654982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44d8e5b20260'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_rules',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор правила'),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Включено ли правило'),
    sa.Column('scenario_type', sa.String(length=100), nullable=False, comment='Тип сценария, который формируется этим правилом'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание логики правила'),
    sa.Column('window_seconds', sa.Integer(), nullable=False, comment='Максимальное временное окно между инцидентами (в секундах)'),
    sa.Column('sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Последовательность типов инцидентов/атак, которые должны связаться'),
    sa.Column('group_by', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Поля, по которым инциденты считаются связанными'),
    sa.Column('min_unique_categories', sa.Integer(), nullable=False, comment='Минимальное число уникальных категорий для срабатывания'),
    sa.Column('severity_hint', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_hint_enum'), nullable=False, comment='Итоговая критичность сценария'),
    sa.Column('confidence', sa.Integer(), nullable=False, comment='Уверенность правила, 0–100'),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Рекомендации аналитику'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Теги правила'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_rules_scenario_type'), 'correlation_rules', ['scenario_type'], unique=False)
    op.create_table('detection_rules',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('fields', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('scenario_type', sa.String(length=100), nullable=True),
    sa.Column('mitre_ids', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('tactics', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('severity_hint', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_hint_enum'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('explanation_template', sa.String(length=500), nullable=True),
    sa.Column('recommendations', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userroles'), server_default='VIEWER', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=70), nullable=True),
    sa.Column('rule_general_id', sa.String(), nullable=False),
    sa.Column('rule_unique_id', sa.Integer(), nullable=False),
    sa.Column('before_id', sa.Integer(), nullable=True),
    sa.Column('after_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.ForeignKeyConstraint(['after_id'], ['audit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['before_id'], ['audit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_unique_id'], ['detection_rules.unique_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correlation_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=70), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('correlation_unique_id', sa.Integer(), nullable=False),
    sa.Column('before_id', sa.Integer(), nullable=True),
    sa.Column('after_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.ForeignKeyConstraint(['after_id'], ['correlation_audit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['before_id'], ['correlation_audit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['correlation_unique_id'], ['correlation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correlation_audit')
    op.drop_table('audit')
    op.drop_table('users')
    op.drop_table('detection_rules')
    op.drop_index(op.f('ix_correlation_rules_scenario_type'), table_name='correlation_rules')
    op.drop_table('correlation_rules')
    # ### end Alembic commands ###
