"""initial commit

Revision ID: 00d97b406735
Revises: 
Create Date: 2026-08-25 15:09:46.148990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d97b406735'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('fields', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('scenario_type', sa.String(length=100), nullable=True),
    sa.Column('mitre_ids', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('tactics', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('severity_hint', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity_hint_enum'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('explanation_template', sa.String(length=500), nullable=True),
    sa.Column('recommendations', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userroles'), server_default='VIEWER', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=70), nullable=True),
    sa.Column('rule_general_id', sa.String(), nullable=False),
    sa.Column('rule_unique_id', sa.Integer(), nullable=False),
    sa.Column('before_id', sa.Integer(), nullable=True),
    sa.Column('after_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.ForeignKeyConstraint(['after_id'], ['audit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['before_id'], ['audit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_unique_id'], ['detection_rules.unique_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit')
    op.drop_table('users')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
