"""добавил поля для crule

Revision ID: 4355008ac21b
Revises: 512e372dd912
Create Date: 2026-09-24 15:18:45.255635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4355008ac21b'
down_revision: Union[str, Sequence[str], None] = '512e372dd912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correlation_rules', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('correlation_rules', sa.Column('updated_by', sa.String(), nullable=False))
    op.add_column('correlation_rules', sa.Column('created_at', sa.String(), nullable=False))
    op.add_column('correlation_rules', sa.Column('updated_at', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('correlation_rules', 'updated_at')
    op.drop_column('correlation_rules', 'created_at')
    op.drop_column('correlation_rules', 'updated_by')
    op.drop_column('correlation_rules', 'created_by')
    # ### end Alembic commands ###
